// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PhoneBook.Models
{
    public partial class Company
    {
        public Company()
        {
            People = new HashSet<Person>();
        }

        public string CompanyName { get; set; }
        public DateTime? RegistrationDate { get; set; }

        public virtual ICollection<Person> People { get; set; }

        public int PeopleCount { get { return People.Count;} }
    }
}